# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53b2346702ae07e0b0a73d6f6fdadb63368f344033f9cee5952db5de3f12e2de4fbb10ba677599af089f23097fc94bf01d82240741771e7737c6b73eb91eb45a

test:
  secret_key_base: bdf950c710ccc47b015a8e3f74ffa70db1e537791c7350dc190dabc2ed7b5da423608fb460150c68491797aecfa8da96c9e5735515f8650f14fe7b34c39e76dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
